### ISSUE TITLE
Would like to contribute

### ISSUE THREAD

**Issue by scottepeterson** [Vamshidhar1995/Servicenow#1]
@Vamshidhar1995 - have a question about this repo - can you comment back in email ?

**Comment by Vamshidhar1995** [comment]
Hi @scottepeterson
Sorry for this, I have transferred ownership of Volteo Digital to you. You will be receiving a Transfer ownership request.

Really I am sorry for this mess.

Kind Regards
Vamshidhar D

**Comment by Vamshidhar1995** [comment]
Issue Closed, Transferred Ownership to @scottepeterson
